-- Create destination_categories table
-- This table stores countries and their corresponding destination categories

CREATE TABLE IF NOT EXISTS destination_categories (
    id SERIAL PRIMARY KEY,
    country VARCHAR(255) NOT NULL,
    destination_category VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for better performance
CREATE INDEX IF NOT EXISTS idx_destination_categories_country ON destination_categories(country);
CREATE INDEX IF NOT EXISTS idx_destination_categories_category ON destination_categories(destination_category);

-- Create trigger for updated_at timestamp
CREATE TRIGGER update_destination_categories_updated_at 
    BEFORE UPDATE ON destination_categories
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Insert destination categories data from the provided file
INSERT INTO destination_categories (country, destination_category) VALUES
('Alaska (USA)', 'Worldwide'),
('Albania', 'Europe'),
('Algeria', 'Worldwide'),
('Andorra', 'Worldwide'),
('Angola', 'Worldwide'),
('Antigua and Barbuda', 'Worldwide'),
('Argentina', 'Worldwide'),
('Armenia', 'Worldwide'),
('Australia', 'Worldwide'),
('Austria', 'Europe'),
('Azerbaijan', 'Worldwide'),
('The Bahamas', 'Worldwide'),
('Bahrain', 'Worldwide'),
('Bangladesh', 'Worldwide'),
('Barbados', 'Worldwide'),
('Belgium', 'Europe'),
('Belize', 'Worldwide'),
('Benin', 'Worldwide'),
('Bhutan', 'Worldwide'),
('Bolivia', 'Worldwide'),
('Bosnia and Herzegovina', 'Europe'),
('Botswana', 'Worldwide'),
('Brazil', 'Worldwide'),
('Brunei', 'Worldwide'),
('Bulgaria', 'Europe'),
('Burkina Faso', 'Worldwide'),
('Burundi', 'Worldwide'),
('Cabo Verde', 'Worldwide'),
('Cambodia', 'Worldwide'),
('Cameroon', 'Worldwide'),
('Canada', 'Worldwide'),
('Central African Republic', 'Worldwide'),
('Chad', 'Worldwide'),
('Chile', 'Worldwide'),
('China', 'Worldwide'),
('Colombia', 'Worldwide'),
('Comoros', 'Worldwide'),
('Cook Islands', 'Worldwide'),
('Costa Rica', 'Worldwide'),
('Côte d''Ivoire', 'Worldwide'),
('Croatia', 'Europe'),
('Cuba', 'Worldwide'),
('Czech Republic', 'Europe'),
('Denmark', 'Europe'),
('Djibouti', 'Worldwide'),
('Dominica', 'Worldwide'),
('Dominican Republic', 'Worldwide'),
('East Timor (Timor-Leste)', 'Worldwide'),
('Ecuador', 'Worldwide'),
('Egypt', 'Worldwide'),
('El Salvador', 'Worldwide'),
('Equatorial Guinea', 'Worldwide'),
('Eritrea', 'Worldwide'),
('Estonia', 'Europe'),
('Eswatini', 'Worldwide'),
('Ethiopia', 'Worldwide'),
('Fiji', 'Worldwide'),
('Finland', 'Europe'),
('Fortuna Islands', 'Worldwide'),
('France', 'Europe'),
('Gabon', 'Worldwide'),
('The Gambia', 'Worldwide'),
('Georgia', 'Worldwide'),
('Germany', 'Europe'),
('Ghana', 'Worldwide'),
('Greece', 'Europe'),
('Greenland', 'Worldwide'),
('Grenada', 'Worldwide'),
('Guatemala', 'Worldwide'),
('Guinea', 'Worldwide'),
('Guinea-Bissau', 'Worldwide'),
('Guyana', 'Worldwide'),
('Haiti', 'Worldwide'),
('Honduras', 'Worldwide'),
('Hungary', 'Europe'),
('Iceland', 'Europe'),
('India', 'Worldwide'),
('Indonesia', 'Worldwide'),
('Northern Ireland', 'Europe'),
('Israel (Excluding West Bank, Gaza and the Occupied Territories)', 'Worldwide'),
('Italy', 'Europe'),
('Ivory Coast', 'Worldwide'),
('Jamaica', 'Worldwide'),
('Japan', 'Worldwide'),
('Jordan', 'Worldwide'),
('Kazakhstan', 'Worldwide'),
('Kenya', 'Worldwide'),
('Kiribati', 'Worldwide'),
('Kosovo', 'Europe'),
('Kuwait', 'Worldwide'),
('Kyrgyzstan', 'Worldwide'),
('Laos', 'Worldwide'),
('Latvia', 'Europe'),
('Lesotho', 'Worldwide'),
('Liberia', 'Worldwide'),
('Liechtenstein', 'Europe'),
('Lithuania', 'Europe'),
('Luxembourg', 'Europe'),
('Madagascar', 'Worldwide'),
('Malawi', 'Worldwide'),
('Malaysia', 'Worldwide'),
('Maldives', 'Worldwide'),
('Mali', 'Worldwide'),
('Malta', 'Europe'),
('Marshall Islands', 'Worldwide'),
('Mauritania', 'Worldwide'),
('Mauritius', 'Worldwide'),
('Mexico', 'Worldwide'),
('Micronesia, Federated States of', 'Worldwide'),
('Moldova', 'Europe'),
('Monaco', 'Europe'),
('Mongolia', 'Worldwide'),
('Montenegro', 'Europe'),
('Morocco', 'Europe'),
('Mozambique', 'Worldwide'),
('Myanmar (Burma)', 'Worldwide'),
('Namibia', 'Worldwide'),
('Nauru', 'Worldwide'),
('Nepal', 'Worldwide'),
('Netherlands', 'Europe'),
('New Zealand', 'Worldwide'),
('Nicaragua', 'Worldwide'),
('Niger', 'Worldwide'),
('Nigeria', 'Worldwide'),
('North Macedonia', 'Europe'),
('Norway', 'Europe'),
('Oman', 'Worldwide'),
('Pakistan', 'Worldwide'),
('Palau', 'Worldwide'),
('Panama', 'Worldwide'),
('Papua New Guinea', 'Worldwide'),
('Paraguay', 'Worldwide'),
('Peru', 'Worldwide'),
('Philippines', 'Worldwide'),
('Poland', 'Europe'),
('Portugal', 'Europe'),
('Qatar', 'Worldwide'),
('Republic of Cyprus', 'Europe'),
('Republic of Ireland', 'Europe'),
('Romania', 'Europe'),
('Rwanda', 'Worldwide'),
('Saint Kitts and Nevis', 'Worldwide'),
('Saint Lucia', 'Worldwide'),
('Saint Vincent and the Grenadines', 'Worldwide'),
('Samoa', 'Worldwide'),
('San Marino', 'Europe'),
('Sao Tome and Principe', 'Worldwide'),
('Saudi Arabia', 'Worldwide'),
('Senegal', 'Worldwide'),
('Serbia', 'Europe'),
('Seychelles', 'Worldwide'),
('Sierra Leone', 'Worldwide'),
('Singapore', 'Worldwide'),
('Slovak Republic (Slovakia)', 'Europe'),
('Slovenia', 'Europe'),
('Solomon Islands', 'Worldwide'),
('South Africa', 'Worldwide'),
('South Korea', 'Worldwide'),
('Spain', 'Europe'),
('Sri Lanka', 'Worldwide'),
('Suriname', 'Worldwide'),
('Sweden', 'Europe'),
('Switzerland', 'Europe'),
('Taiwan', 'Worldwide'),
('Tajikistan', 'Worldwide'),
('Tanzania', 'Worldwide'),
('Thailand', 'Worldwide'),
('Tibet', 'Worldwide'),
('Togo', 'Worldwide'),
('Tonga', 'Worldwide'),
('Trinidad and Tobago', 'Worldwide'),
('Tunisia', 'Europe'),
('Turkey', 'Europe'),
('Turkish Republic of Northern Cyprus (TRNC)', 'Europe'),
('Turkmenistan', 'Worldwide'),
('Turks & Caicos Islands', 'Worldwide'),
('Tuvalu', 'Worldwide'),
('Uganda', 'Worldwide'),
('United Arab Emirates', 'Worldwide'),
('United Kingdom', 'Europe'),
('United States of America', 'Worldwide'),
('Uruguay', 'Worldwide'),
('Uzbekistan', 'Worldwide'),
('Vanuatu', 'Worldwide'),
('Vatican City', 'Europe'),
('Venezuela', 'Worldwide'),
('Vietnam', 'Worldwide'),
('Wallis', 'Worldwide'),
('Yemen', 'Worldwide'),
('Zambia', 'Worldwide'),
('Zimbabwe', 'Worldwide');

-- Create a view for easy access to destination categories
CREATE OR REPLACE VIEW destination_categories_view AS
SELECT DISTINCT destination_category
FROM destination_categories
ORDER BY destination_category;

-- Print success message
SELECT 'Destination categories table created and populated successfully!' as status;
SELECT COUNT(*) as total_countries FROM destination_categories;
SELECT destination_category, COUNT(*) as country_count 
FROM destination_categories 
GROUP BY destination_category 
ORDER BY destination_category;

