name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'server/**'
      - '.github/workflows/azure-container-apps.yml'
  workflow_dispatch:

env:
  RESOURCE_GROUP: 'TravelInsurance-RG'
  ACR_NAME: 'travelinsuranceacr'
  BACKEND_APP_NAME: 'travel-insurance-api'
  PROXY_APP_NAME: 'travel-insurance-proxy'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/travel-insurance-backend:${{ github.sha }} \
                       -t ${{ env.ACR_NAME }}.azurecr.io/travel-insurance-backend:latest \
                       ./backend
          docker push ${{ env.ACR_NAME }}.azurecr.io/travel-insurance-backend:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/travel-insurance-backend:latest

      - name: Build and push proxy image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/travel-insurance-proxy:${{ github.sha }} \
                       -t ${{ env.ACR_NAME }}.azurecr.io/travel-insurance-proxy:latest \
                       ./server
          docker push ${{ env.ACR_NAME }}.azurecr.io/travel-insurance-proxy:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/travel-insurance-proxy:latest

      - name: Deploy backend to Container Apps
        run: |
          az containerapp update \
            --name ${{ env.BACKEND_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/travel-insurance-backend:${{ github.sha }}

      - name: Deploy proxy to Container Apps
        run: |
          az containerapp update \
            --name ${{ env.PROXY_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/travel-insurance-proxy:${{ github.sha }}

      - name: Get backend URL
        id: backend-url
        run: |
          BACKEND_URL=$(az containerapp show \
            --name ${{ env.BACKEND_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --query properties.configuration.ingress.fqdn \
            --output tsv)
          echo "Backend URL: https://$BACKEND_URL"
          echo "::set-output name=url::https://$BACKEND_URL"

      - name: Get proxy URL
        id: proxy-url
        run: |
          PROXY_URL=$(az containerapp show \
            --name ${{ env.PROXY_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --query properties.configuration.ingress.fqdn \
            --output tsv)
          echo "Proxy URL: https://$PROXY_URL"
          echo "::set-output name=url::https://$PROXY_URL"

      - name: Deployment Summary
        run: |
          echo "### Deployment Summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Backend API**: ${{ steps.backend-url.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Proxy Server**: ${{ steps.proxy-url.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY

