name: Auto Version & Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Get previous tag (if any)
      - name: Get previous tag
        id: prev_tag
        run: |
          git fetch --tags
          PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_ENV

      # Step 3: List changed files since last tag
      - name: Get changed files
        id: changed_files
        run: |
          if [ -z "$PREV_TAG" ]; then
            echo "CHANGED_FILES=$(git ls-files)" >> $GITHUB_ENV
          else
            CHANGED=$(git diff --name-only $PREV_TAG HEAD)
            echo "CHANGED_FILES=$CHANGED" >> $GITHUB_ENV
          fi

      # Step 4: Bump version and create tag
      - name: Bump version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: v

      # Step 5: Create GitHub Release with changed files in release notes
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
            Automated release generated by GitHub Actions.

            **Changed files since last release:**
            ${{ env.CHANGED_FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
